<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Assessments: the core evaluation unit.
     * Each record = one assessment assigned to one employee.
     * Can be created manually (by HR/manager) or auto-generated by an evaluation cycle.
     *
     * assessment_questions: individual questions linked to KPIs.
     *   - Supports MCQ and rating-scale types (current system).
     *   - Supports AI-generated questions (Section 7.5).
     *   - question_bank_id: if sourced from the global question bank (future).
     *
     * assessment_answers: one row per question, per assessment.
     *   - Unique on (assessment_id, assessment_question_id) — one answer per question.
     */
    public function up(): void
    {
        Schema::create('assessments', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Organization::class)->constrained()->cascadeOnDelete();
            $table->foreignIdFor(\App\Models\EvaluationCycle::class)->nullable()->constrained()->nullOnDelete();
            $table->foreignIdFor(\App\Models\User::class, 'assigned_to_user_id')->constrained()->cascadeOnDelete();
            $table->foreignIdFor(\App\Models\User::class, 'assigned_by_user_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignIdFor(\App\Models\JobRole::class)->nullable()->constrained()->nullOnDelete();

            $table->unsignedTinyInteger('level');              // 1, 2, 3
            $table->unsignedSmallInteger('duration_minutes');  // 30, 45, 60
            $table->enum('status', ['pending', 'in_progress', 'completed', 'expired'])->default('pending');

            $table->timestamp('due_at')->nullable();
            $table->timestamp('started_at')->nullable();
            $table->timestamp('completed_at')->nullable();
            $table->unsignedSmallInteger('time_taken_seconds')->nullable(); // actual time spent

            $table->boolean('auto_generated')->default(false);  // flag from evaluation cycle
            $table->timestamps();
            $table->softDeletes();

            $table->index(['organization_id', 'status']);
            $table->index(['assigned_to_user_id', 'status']);
            $table->index(['evaluation_cycle_id', 'status']);
        });

        Schema::create('assessment_questions', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Assessment::class)->constrained()->cascadeOnDelete();
            $table->foreignIdFor(\App\Models\Kpi::class)->constrained()->cascadeOnDelete();
            $table->text('question_text');
            $table->enum('question_type', ['mcq', 'rating_scale']);
            $table->json('options')->nullable();               // MCQ: [{label, value, score}]
            $table->unsignedTinyInteger('max_score')->default(5);
            $table->unsignedSmallInteger('order')->default(0);
            $table->boolean('is_ai_generated')->default(false); // Section 7.5
            $table->timestamps();

            $table->index(['assessment_id', 'kpi_id']);
        });

        Schema::create('assessment_answers', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Assessment::class)->constrained()->cascadeOnDelete();
            $table->foreignIdFor(\App\Models\AssessmentQuestion::class)->constrained()->cascadeOnDelete();
            $table->string('answer_value');                    // selected option key or rating integer
            $table->unsignedTinyInteger('score');              // computed score for this answer
            $table->timestamps();

            // Only one answer per question per assessment
            $table->unique(['assessment_id', 'assessment_question_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('assessment_answers');
        Schema::dropIfExists('assessment_questions');
        Schema::dropIfExists('assessments');
    }
};
